export const GET_DOCS = "GET_DOCS",
GET_DOCS_SUCCESS = "GET_DOCS_SUCCESS",
 GET_DOCS_CATE = "GET_DOCS_CATE",
GET_DOCS_CATE_SUCCESS = "GET_DOCS_CATE_SUCCESS",
CREATE_DOC = "CREATE_DOC",
CREATE_DOC_SUCCESS = "CREATE_DOC_SUCCESS",
UPDATE_DOC = "UPDATE_DOC",
UPDATE_DOC_SUCCESS = "UPDATE_DOC_SUCCESS";