export const GET_FEATURE_DOCS = "GET_FEATURE_DOCS",
    GET_FEATURE_DOCS_SUCCESS = "GET_FEATURE_DOCS_SUCCESS",
    GET_DOCS_SHARE = "GET_DOCS_SHARE",
    PAGINATION = "PAGINATION",
    SEARCH_DOCS_HEADER = "SEARCH_DOCS_HEADER",
    GET_DOCS_SHARE_SUCCESS = "GET_DOCS_SHARE_SUCCESS";