export const //SIGNUP
  SIGNUP = 'SIGNUP',
  SIGNUP_SUCCESS = 'SIGNUP_SUCCESS',
  CHECK_AUTH = 'CHECK_AUTH',
  //LOGIN
  LOGIN = 'LOGIN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  IS_LOGIN = 'IS_LOGIN',
  //LOGOUT
  LOGOUT = 'LOGOUT',
  //FORGOT PASSWORD
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS',
  //RESET PASSWORD
  RESET_PASSWORD = 'RESET_PASSWORD',
  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS',
  //ACTIVE USER
  ACTIVE_USER = 'ACTIVE_USER',
  ACTIVE_USER_SUCCESS = 'ACTIVE_USER_SUCCESS',
  // GET OC
  GET_OC = 'GET_OC',
  GET_OC_SUCCESS = 'GET_OC_SUCCESS',
  //CHANGE PASSWORD
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS',
  //GET ORDER BY USER
  GET_ORDER = 'GET_ORDER',
  GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS',
  GET_LIST_MESSAGES = 'GET_LIST_MESSAGES',
  GET_LIST_MESSAGES_SUCCESS = 'GET_LIST_MESSAGES_SUCCESS',
  ADD_WISH_LIST = 'ADD_WISH_LIST',
  ADD_WISH_LIST_SUCCESS = 'ADD_WISH_LIST_SUCCESS',
  GET_LIST_ORDERS = 'GET_LIST_ORDERS',
  GET_LIST_ORDERS_SUCCESS = 'GET_LIST_ORDERS_SUCCESS',
  ADD_REVIEW = 'ADD_REVIEW',
  ACTIVE_ORDER = 'ACTIVE_ORDER',
  ACTIVE_ORDER_SUCCESS = 'ACTIVE_ORDER_SUCCESS',
  // UPDATE USER INFO
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS',
  CHECK_TOKEN_PASSWORD = 'CHECK_TOKEN_PASSWORD';
